version = "1"
php-version = "8.4.0"

[source]
workspace = "."
paths = [
    "bin",
    "src",
    "tests",
]
includes = ["vendor"]

[formatter]
preserve-breaking-argument-list = true
preserve-breaking-attribute-list = true
preserve-breaking-member-access-chain = true
